CREATE TABLE PUBLIC.SUBJECT_TABLE (
	SUBJECTID DECIMAL NOT NULL,
	SUBTITLE VARCHAR(255) NOT NULL,
	DURATIONINHOURS DECIMAL NOT NULL
);

CREATE TABLE PUBLIC.BOOK_TABLE (
	BOOKID DECIMAL NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	PRICE DECIMAL NOT NULL,
	VOLUME DECIMAL,
	PUBLISHDATE DATE,
	SUBJECTID DECIMAL
);
