INSERT INTO SUBJECT_TABLE (SUBJECTID, SUBTITLE, DURATIONINHOURS) VALUES(1001, 'Hindi-Literature', 100);
INSERT INTO SUBJECT_TABLE (SUBJECTID, SUBTITLE, DURATIONINHOURS) VALUES(1002, 'Geography-Primary', 50);
INSERT INTO SUBJECT_TABLE (SUBJECTID, SUBTITLE, DURATIONINHOURS) VALUES(1004, 'Hindi-Grammar', 95);
INSERT INTO SUBJECT_TABLE (SUBJECTID, SUBTITLE, DURATIONINHOURS) VALUES(1005, 'Geography-Advanced', 44);

COMMIT;